### ISSUE TITLE
pithos won't start on Fedora 20 gtk 3.10.9-2

### ISSUE THREAD

**Issue by gregsheremeta** [pithos/pithos#177]
On master, Fedora 20
gtk3.x86_64                            3.10.9-2.fc20

```python
greg@dauntless:~/projects/pithos(master|✔) % git log |head -1
commit e78c8acbbe3fcd53370e199976c218180f8c254d
greg@dauntless:~/projects/pithos(master|✔) % python3 -m pithos

(__main__.py:1935): Gtk-WARNING **: Unknown property: GtkGrid.margin-start

(__main__.py:1935): Gtk-WARNING **: Unknown property: GtkGrid.margin-start
Traceback (most recent call last):
  File "./pithos/pithos.py", line 1112, in do_command_line
    self.do_activate()
  File "./pithos/pithos.py", line 1119, in do_activate
    self.window = NewPithosWindow(self, self.options)
  File "./pithos/pithos.py", line 1053, in NewPithosWindow
    window.finish_initializing(builder, options)
  File "./pithos/pithos.py", line 173, in finish_initializing
    self.prefs_dlg.set_plugins(self.plugins)
  File "./pithos/PreferencesPithosDialog.py", line 123, in set_plugins
    self.listbox.set_header_func(self.on_listbox_update_header)
TypeError: set_header_func() takes exactly 3 arguments (2 given)
```

**Comment by TingPing** [comment]
Yea that happened with https://github.com/pithos/pithos/commit/ab0029917992d5a791da46a6b47eb5dd98fb75b1. After I pushed it I realized that property was new in 3.12 but its possible that the popover branch is merged this cycle which requires 3.12 anyway.

**Comment by TingPing** [comment]
Hmm, the set_header_func() error was likely either a change in the docs, or pygobject handling user_data/destroy callbacks since they are not used in Python. If you want to add a workaround for that its fine, but the current args are the correct ones and as I said moving forward that version should be dropped eventually.

**Comment by gregsheremeta** [comment]
3.12 only is fine for me on Fedora.

Do you know if this will affect other distros?

**Comment by TingPing** [comment]
It bumps Ubuntus min release to 14.10.

**Comment by gregsheremeta** [comment]
Hmm. That's a tough one because 14.04 is an LTS. Thoughts on that?

**Comment by TingPing** [comment]
It's not like Ubuntu even packages us anyway. I think the popover stuff is worth the dep bump but like I said if you want to work around that one bug until then that is fine with me.

**Comment by JasonLG1979** [comment]
Like @TingPing said Ubuntu doesn't package an up to date version of Pithos anyway. My vote(if I had one) would either just not update the PPA for Ubuntu 14.04 past the breakage or if you want to get fancy do a backport branch for pre-3.12 distros, which would pretty much just be Ubuntu 14.04 since even Debian 8(just released a few days ago) ships with 3.14. Just freezing the PPA for 14.04 would be much easier/more cost effective though IMHO.

**Comment by TingPing** [comment]
Fixed by e4fce0d5191711b5106d5e8ed7fe7e8f88963edf.

Though the unknown property was not fixed before 1.1.0. So users should use Gtk 3.12 for it to be correctly aligned..

**Comment by isleshocky77** [comment]
:-( Mint 17.3 is on GTK 3.10 with no upgrade path that I can find. Mint 17.3 which is just now in beta and going stable next month is still based on Ubuntu 14.04.

Guess I'm stuck on on Pithos 1.0.3 for a while.

**Comment by TingPing** [comment]
@isleshocky77 Mint purposefully stays really old, not the best distro to use if you want to use modern applications.
