### ISSUE TITLE
Pithos not playing when JACK is running.

### ISSUE THREAD

**Issue by imoldovavan** [pithos/pithos#264]
Pithos will not play the song if JACK audio is started. If I start Pithos first the song stops playing when jack fires up. Looking at the song seconds they just stop, and when I stop jack pithos continue to play the song. 
Thank you,

**Comment by JasonLG1979** [comment]
The last time I played with it years ago you had to explicitly route audio through it. The same thing would happen if you disabled software mixing in ALSA and didn't have PulseAudio installed. You can only play audio from one source at a time with most sound cards without software mixing. From what little I understand of JACK it's virtual patch bay. My guess is that it's taking control sole control of your sound device.

**Comment by JasonLG1979** [comment]
@imoldovavan have you figured this out yet?

**Comment by imoldovavan** [comment]
I have not played with Jack and Pithos lately. It would be nice to make it work, but it's not a show stopper. If  there is something I can try let me know in detail. 
I love Pithos.... use it all the time :)

**Comment by JasonLG1979** [comment]
As I said before:

> The last time I played with it years ago you had to explicitly route audio through it. The same thing would happen if you disabled software mixing in ALSA and didn't have PulseAudio installed. You can only play audio from one source at a time with most sound cards without software mixing. From what little I understand of JACK it's virtual patch bay. My guess is that it's taking sole control of your sound device.

Since Jack is a virtual patch bay it's up to you how your sound is routed. What you describe is normal behavior, i.e. only one application has access to your sound card at a time. Most sound cards do not have hardware mixing capabilities so they require software mixing to play sound from multiple sources at once. (PulseAudio is an example of a software mixer) 

This is not a Pithos bug we have no control of your audio configuration.
