### ISSUE TITLE
FEATURE request: reload / reshuffle playlist

### ISSUE THREAD

**Issue by siddharthTyagi** [pithos/pithos#374]
Is it possible to add a new reshuffle button to the main window to reshuffle the playlist if you are unable to skip a song because of skip limit.

**Comment by JasonLG1979** [comment]
No. Songs are played in the order that they come from Pandora. Pandora did recently add the ability to replay songs but it involves get unknown API changes.

Generally speaking just don't skip so many songs as to hit your skip limit.

**Comment by siddharthTyagi** [comment]
I am not sure if that's a bug or feature. But, if you run out of skips and change your station. When you get back to the same station the playlist is shuffled and there are new songs. So I am assuming that can be related to reshuffle.

**Comment by JasonLG1979** [comment]
> I am not sure if that's a bug or feature.

It's neither. That's just how it is. Pithos has no control over what's in the playlist. It comes from Pandora.

> But, if you run out of skips and change your station. When you get back to the same station the playlist is shuffled and there are new songs. So I am assuming that can be related to reshuffle.

Stations are not "shuffled." When/if you run out of skips Pandora blocks your account for a short period of time. When that time is over Pithos can get a new playlist.

**Comment by JasonLG1979** [comment]
For the benefit of a big picture view of what Pithos is/does:

Pithos is a Pandora client. On a very basic level Pithos puts a "face" or UI on the Pandora API and integrates that UI with your desktop in ways you'd expect from an audio player. With very few exception if you can't do it in at the Pandora website or in the Pandora mobile apps you're not going to be able to do it with Pithos. And since the Pandora API is not public there are many thing you can do in official Pandora clients that Pithos can't because parts of the API have not been reverse engineered yet.

The API docs are here:
https://github.com/PromyLOPh/pandora-apidoc

**Comment by siddharthTyagi** [comment]
>Stations are not "shuffled." When/if you run out of skips Pandora blocks your account for a short period of time. When that time is over Pithos can get a new playlist.
Assuming this, it is hard to explain the behavior that I described. Even if you are blocked and can no longer change song. You can still change the station and get back to the same station with new songs. That sorts of gives you the ability to skip even if you can not.

**Comment by JasonLG1979** [comment]
That is strange. But whatever the behavior, I'm trying to tell you Pithos does NOT control Pandora. We have no control over what they do. Pithos simply tries to get a playlist for a station when you change to it. If that succeeds or not is not up to Pithos.

**Comment by JasonLG1979** [comment]
Again a big picture view:
You change stations >>> Pithos asks Pandora for a playlist from that station >>> a million things can go wrong >>> hopefully you get a playlist >>> Pithos plays that playlist.

**Comment by siddharthTyagi** [comment]
I understand that. Maybe I should restate the feature to be reload playlist instead of reshuffle. The only reason I called it reshuffle is that pandora returns a new playlist each time in such scenarios. 
What my suggestion is to get that station flip effect through a button. 
For now the playlist is changed. Assuming that it remains the same it can be called a 'reshuffle' (just like in old winamp), or if the playlist in future starts to be the same each time (it can simply be reload playlist).
I can not see how this is controlling pandora through pithos other than the fact of naming the feature (alone). Which can also be a combination of both (reload/reshuffle playlist)

**Comment by JasonLG1979** [comment]
Reshuffle(as in to shuffle again) implies changing the order of existing songs. I can tell you right now we're not going to add a feature change the order of an existing playlist. As far as loading a playlist. Pithos automatically grabs a new playlist when there are less than or equal to 1 song left in a playlist. If you want to force Pithos to grab a new playlist for a station you are on double click the last song in the existing playlist or skip to it. Adding a button would be redundant.

**Comment by JasonLG1979** [comment]
I think you're asking the wrong question. Let's look at what's going on. You want to be able to reload a fresh playlist at will(which btw you already can) and you're hitting your skip limit at least every now and then. The problem is not Pithos or Pandora. The problem is that you're not using Pandora as you should. You obviously want to load new playlists because you don't like what you got from Pandora. The question you should be asking is "How can I get Pandora to play songs I like?" The answer to that question is rate songs. Love the songs you like ban the songs you hate and tired the songs you necessarily hate but are tired of for now. The more you rate songs the more Pandora will give you playlists you like. Pandora learns from your ratings.

**Comment by siddharthTyagi** [comment]
> If you want to force Pithos to grab a new playlist for a station you are on double click the last song in the existing playlist or skip to it. Adding a button would be redundant.

Skipping so many songs will block you eventually. That is why I am suggesting to create a button for doing that (to save skips).
I get the point that you are trying to make (in using Pandora properly). But this feature request is something unique and I do not see how two can be related. 
Having a simple button to reload playlist does give you the freedom to reload current STATION with different songs. Even though you get the perfect songs all the time. Still, I think it is a good feature to give freedom to user (instead of skipping all pending songs)

**Comment by siddharthTyagi** [comment]
I think you are mixing skipping a song with skipping the playlist.

**Comment by JasonLG1979** [comment]
> I think you are mixing skipping a song with skipping the playlist.

They are functionally the same thing. Pandora gives us 4 song playlists. When you start playing the last song in the playlist Pithos asks Pandora for an new playlist. Getting a playlist from Pandora counts against your playlist limit. It does not matter if you listen to all or none of the songs. Pithos does not report if you skip individual songs. So skipping songs in the playlist does not matter. The only thing new your "New Playlist" button would do was clear the UI, otherwise it would be redundant .

**Comment by siddharthTyagi** [comment]
> Getting a playlist from Pandora counts against your playlist limit. It does not matter if you listen to all or none of the songs

Strange, I have not experienced this behavior in official client. Even if your skip limit is hit.

**Comment by JasonLG1979** [comment]
Because in the official client you'd hit your individual song skip limit way before you hit your playlist limit. In Pithos you could listen for 12 hours straight and skip every 4th song(1 song per playlist) and Pandora wouldn't bat an eye, because like I said Pithos does not keep track of how many songs you skip and neither does the Pandora service. Song skip limits are enforced client side.

**Comment by siddharthTyagi** [comment]
Makes sense
