### ISSUE TITLE
Allow Fully Hiding Window without Icon in Notification Area

### ISSUE THREAD

**Issue by Azdle** [pithos/pithos#42]
It would be really nice if it were possible to hide the window without having to have the "Show notification area icon" enabled.

Cinnamon's (and I assume gnome 3's) volume applet shows pithos and allows me to control it as well as re-showing the window when it is hidden so it'd be nice to not have an extra icon cluttering up my applets but still be able to hide the pithos window.

**Comment by gregsheremeta** [comment]
Love, ban, etc. aren't accessible from the volume applet. I don't care for this idea after all. Thanks for the suggestion!

**Comment by JasonLG1979** [comment]
With the (hopefully) upcoming changes to MPRIS especially if/when we add a ratings setting method.(and we can talk the applet devs to add support for it since setting ratings in not apart of the MPRIS spec) this could really be a viable option. IMHO we should work on a whitelist basis. Only enable the feature for applets that are know meet a certain level of functionality.
