### ISSUE TITLE
[Feature request] Hide "Choose Playlist" if empty

### ISSUE THREAD

**Issue by orschiro** [pithos/pithos#456]
Dear all, 

This might be related to the recent indicator discussion [1] and maybe it requires a new applet to arrive on MATE. 

But let me still ask if it is possible to hide the "Choose Playlist" entry if it is empty?

Yours,

Robert

![pithos empty playlist](https://cloud.githubusercontent.com/assets/170947/25315066/53ba858e-284f-11e7-9347-57473433c2da.png)

[1] https://github.com/pithos/pithos/issues/451

**Comment by JasonLG1979** [comment]
This is a duplicate of https://github.com/pithos/pithos/issues/423 the upstream bug is here: https://bugs.launchpad.net/ubuntu/+source/indicator-sound/+bug/1663906

We don't control the Ubuntu Sound menu. We put up MPRIS Interfaces, it's up to the client(in this case the sound menu) what they want to do with it.

**Comment by orschiro** [comment]
Thank you, @JasonLG1979. I subscribed to the bug...

**Comment by TingPing** [comment]
I wouldn't expect it to be fixed upstream btw since Unity is dead.

**Comment by JasonLG1979** [comment]
Yep, I filed that bug before it was announced that unity 7 and 8 were being decommissioned. Well I knew that Unity 7 was in maintenance mode, but I figured that maybe they would fix it since it's definitely a bug not a feature request. But now I'd agree with @TingPing. Now that bug just serves as proof it's an upstream issue and not our problem.
