### ISSUE TITLE
"Bus error"

### ISSUE THREAD

**Issue by kirby193** [pithos/pithos#489]
Attempting to launch pithos has it crash before loading a song or any channels.
A pastebin of the terminal output can be found [here](https://pastebin.com/raw/Sp7B3Jmf)
This is off a fresh apt install pithos (1.1.2-1?)
System is Debian Testing x64 with KDE Plasma 5 as DE

**Comment by JasonLG1979** [comment]
Build the latest git and see if you still get an error. 1.1.2 is almost 2 years old.

**Comment by kirby193** [comment]
I'm not sure if I'd doing this right, but heres the output for ./autogen.sh, make -s, and make run
https://pastebin.com/raw/m5DM1cJt

**Comment by kirby193** [comment]
The output is the exact same as the first post

**Comment by JasonLG1979** [comment]
I'll throw it in a VM and see what I come up with.

**Comment by kirby193** [comment]
Furthermore, attempting to run it locally gives me a bit longer of an output. Maybe this will help you out.
https://pastebin.com/raw/vy363GsT

**Comment by JasonLG1979** [comment]
A little Googling tells me that a "Bus Error" is: 
 
"a fault raised by hardware, notifying an operating system (OS) that a process is trying to access memory that the CPU cannot physically address: an invalid address for the address bus, hence the name. In modern use on most architectures these are much rarer than segmentation faults, which occur primarily due to memory access violations: problems in the logical address or permissions."

https://en.wikipedia.org/wiki/Bus_error

The possible causes are way deeper than what Pithos has anything to do with since we don't do anything directly with memory at any sort of low level like that. It's more than likely an issue with your python interpreter or something in GLib.

**Comment by kirby193** [comment]
Got it. I'll see if I can figure it out on my side.
Thanks
