### ISSUE TITLE
Option to single left click tray icon to toggle "Show Pithos"

### ISSUE THREAD

**Issue by austin6598** [pithos/pithos#532]
Left clicking the tray icon opens a context menu but I would prefer to just see this context menu when right clicking, whereas left clicking should bring the pithos window to front. If the tray icon is clicked and pithos is already the active window - minimize it.

**Comment by JasonLG1979** [comment]
What Desktop environment are you using the tray icon in? I ask because depending on the DE and if you have appindicator installed you are either getting a Gtk.StatusIcon or a appindicator.

I think we may be able to exert some control as far as deciding what to do on button event with the Gtk.StatusIcon but I don't think we can with appindicator. Correct me if I'm wrong @TingPing?

**Comment by TingPing** [comment]
> but I don't think we can with appindicator.

Correct, your shell decides what is the secondary click. You probably need to middle mouse click.
