### ISSUE TITLE
GStreamer plugin issue

### ISSUE THREAD

**Issue by mwleeds** [pithos/pithos#540]
When I try to run the latest pithos from flathub, this pop-up appears:

![screenshot from 2017-11-14 23-03-39](https://user-images.githubusercontent.com/7833263/32823035-4ba8f988-c990-11e7-972c-c137964359cb.png)

And nothing plays. Using pithos from the Fedora repos does work, however.

**Comment by mwleeds** [comment]
There's some odd console output too:
```
WARNING - pithos:_set_player_state:770 - Error changing player state from: NULL to: PAUSED
ERROR - pithos:on_gst_error:1096 - Gstreamer error: gst-core-error-quark: No URI handler implemented for "http". (12), gsturidecodebin.c(1419): gen_source_element (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0, 12
WARNING - pithos:_set_player_state:770 - Error changing player state from: NULL to: PAUSED
```

**Comment by JasonLG1979** [comment]
Playbin should use souphttpsrc internally by default for http https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-souphttpsrc.html my guess is there's something missing as far as a dependency in the flatpak package? I tested the flatpak a couple days ago on Fedora 27 in a VM and didn't have an issue?

**Comment by bblonski** [comment]
I'm having the same problem.  I feel like the problem started occurring after and update.  Might have included a kernel update.  Pithos was rock solid before.  My current kernel is 4.10.0-42 on Linux Mint 18.3.  I've tried the latest flatpak package and the distro included deb package.  It's strange because it will work like 40% of the time.  Usually clicking the cancel button once or twice will skip the next song or two and continue playing as normal.  The issue has persisted for a couple weeks now.

**Comment by TingPing** [comment]
Your kernel isn't remotely relevant. I cannot reproduce.

**Comment by bblonski** [comment]
Here's the full error traceback
```
WARNING - pithos:eb:506 - Traceback (most recent call last):
  File "/app/share/pithos/pithos/gobject_worker.py", line 27, in run
    result = command(*args)
  File "/app/share/pithos/pithos/pithos.py", line 884, in get_album_art
    loader.write(image)
GLib.GError: gdk-pixbuf-error-quark: Unrecognized image file format (3)
```

**Comment by bblonski** [comment]
Yes, version 1.4.1.

**Comment by bblonski** [comment]
Yeah, could be a corporate firewall thing or something like that.  Strange the official web client doesn't seem to be affected.  I'll probably have to switch clients if it doesn't resolve itself.  Shame because you've done a real nice job with Pithos.

**Comment by TingPing** [comment]
How Pithos and the web client work is quite a bit different.

**Comment by kai4785** [comment]
I had the same funny quark error message. I took @TingPing at his word, and setup tiny proxy on a system on another network, configured pandora to use the proxy, and boom, fixed.
It's strange, because I hit this quark issue Monday and Tuesday, then it worked all day Wednesday (yesterday), and Friday (today) it happened again.
I was going to plug issue #51 because I already use socks proxying for other things, but tinyproxy was so brain dead to setup, I may move some of what I do over socks to my new tinyproxy service now.
