### ISSUE TITLE
Dbus objects?

### ISSUE THREAD

**Issue by nhumrich** [pithos/pithos#558]
The wiki looks pretty out of date for the dbus options. I saw somewhere that a while ago you could use dbus to control pandora. I am looking to do this so that I can control pithos with custom key bindings using my i3 config. 

The command I found was:
```
dbus-send --print-reply --dest=net.kevinmehall.Pithos /net/kevinmehall/Pithos net.kevinmehall.Pithos.SkipSong
```

I modified the command to use the new dbus service name `io.github.Pithos` but am getting this error:
```bash
$ dbus-send --print-reply --dest=io.github.Pithos /io/github/Pithos io.github.Pithos.PlayPause
Error org.freedesktop.DBus.Error.UnknownMethod: No such interface 'io.github.Pithos' on object at path /io/github/Pithos
```

What would be the new command for this? Is the dbus still supported outside of mpris?

**Comment by JasonLG1979** [comment]
The wiki is perfectly up to date.

**Comment by TingPing** [comment]
MPRIS is the preferred interface and should support everything the old one did and more.

@JasonLG1979 The docs are missing our custom extensions?

**Comment by JasonLG1979** [comment]
I find d-feet a great app for exploring dbus interfaces.

**Comment by JasonLG1979** [comment]
A side from basically quoting the whole mpris spec I'd say if you want to know what the methods are fire up d-feet.

**Comment by JasonLG1979** [comment]
But for the sake of closing this issue here are the basics:

Previous isn't implemented because you can't currently skip back to previous songs, but here it is anyway:
```--dest=io.github.Pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous```

Stop is mapped to Pause since there is no Stop in Pithos, but here it is anyway:
```--dest=io.github.Pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop```

Play:
```--dest=io.github.Pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play```

Pause:
```--dest=io.github.Pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause```

Play/Pause toggle:
```--dest=io.github.Pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause```

Skip:
```--dest=io.github.Pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next```

Those should work with any player you'd want to control provided of course you change the name (in this case io.github.Pithos) to the player you want to control.

For example if you wanted to ship to the next song in Spotify you could use this:
```dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next```

Spotify for some reason uses org.mpris.MediaPlayer2.spotify as their name because their MPRIS implementation is garbage but that's a whole other issue...

**Comment by TingPing** [comment]
> Spotify for some reason uses org.mpris.MediaPlayer2.spotify as their name

That is correct and Pithos owns `org.mpris.MediaPlayer2.pithos`.

**Comment by JasonLG1979** [comment]
Their top level name in DBus is org.mpris.MediaPlayer2.spotify

**Comment by JasonLG1979** [comment]
Well I stand corrected. It seems it is correct. Both org.mpris.MediaPlayer2.pithos and io.github.Pithos work for our name. DBus is a strange beast...
