### ISSUE TITLE
error: Unknown socket type fallback-x11

### ISSUE THREAD

**Issue by klinden** [pithos/pithos#580]
I've been running Pithos fine for a while now on my Centos 7 machine (installed from Flatpak). This morning I noticed the following error when trying to run:

`error: Unknown socket type fallback-x11, valid types are: x11, wayland, pulseaudio, session-bus, system-bus`

**Comment by JasonLG1979** [comment]
@TingPing this is the commit responsible:

https://github.com/flathub/io.github.Pithos/commit/9209bac8516039fd7065ca42ee40b6d374927f02

Based on this comment:

https://github.com/flatpak/flatpak/pull/2063#issuecomment-418071363

Both sockets "--socket=fallback-x11" and "--socket=x11" should be specified to maintain backwards compatibility.

**Comment by TingPing** [comment]
Oh your `flatpak` is just outdated, I know RHEL 7.6 got a `flatpak` update but maybe CentOS hasn't been updated yet.

In the short term you can use this package: https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/

But you should probably get an official update relatively soon.

@JasonLG1979 	The mentioned workaround won't help here because their version is so old it doesn't ignore unknown args and errors anyway.

**Comment by JasonLG1979** [comment]
> @JasonLG1979 The mentioned workaround won't help here because their version is so old it doesn't ignore unknown args and errors anyway.

It's still not a bad idea though for users with older but not crusty versions?

**Comment by TingPing** [comment]
https://github.com/flathub/io.github.Pithos/commit/f395a949ed98ed412eb05b6822b99b97d654c51c

**Comment by klinden** [comment]
@TingPing Thanks the Flatpak update from the amigadave repo fixed the issue for me.
