### ISSUE TITLE
Add Audio Subsystem Selector

### ISSUE THREAD

**Issue by beanpole135** [pithos/pithos#68]
Add an option in the settings to switch/select which audio subsystem to use for playback (ALSA, PulseAudio, OSS, JACK, etc..).

I have a few systems here with varying system setups, and it always seems like one or two of them just do not "output" any of the audio from Pithos to a usable subsystem. 
(I am using PC-BSD, so OSS is the best for my systems, but it is probably a good idea to simply give the user the option to select the one that works best in their particular case).

Thanks!

**Comment by gregsheremeta** [comment]
Years later ....

Turns out we could configure this, but I don't think I want to.

> By default, if no audio sink or video sink has been specified via the “audio-sink” or “video-sink” property, playbin will use the autoaudiosink and autovideosink elements to find the first-best available output method. This should work in most cases

...

> GNOME-based applications, for example, will usually want to create gconfaudiosink and gconfvideosink elements and make playbin use those, so that output happens to whatever the user has configured in the GNOME Multimedia System Selector configuration dialog.

If we were going to change anything, I'd specifically tell playbin to use GNOME's configuration. However, since this doesn't seem to be a problem for anyone else, I'd say playbin it doing a fine job of guessing the audio system.

I don't know anything about oss, but hopefully you can configure your system in a way to make playbin see it.
